[general]
import = ["~/.config/alacritty/ashen.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[cursor]
style = { shape = "Underline" }
unfocused_hollow = false

[window]
padding = { x = 20, y = 20 }
opacity = 0.9

[colors.primary]
background = "#121212"
